version: "3.9"

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '2.7.2'
        BUNDLER_VERSION: '2.2'
        NODE_MAJOR: '14'
        YARN_VERSION: '1.22.5'
    environment:
      - TZ=Asia/Tokyo
  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3002:3002'

volumes:
  bundle:
  node_modules:
